version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "dependabot:"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
    groups:
      all:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "dependabot:"
    groups:
      all:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
    cooldown:
      default-days: 7
